[pytest]
markers =
    unit: mark a test as a unit test.
filterwarnings =
    ignore::DeprecationWarning:google.protobuf
    ignore::DeprecationWarning:websockets
    ignore::DeprecationWarning:uvicorn
