"""add instance name

Revision ID: a16a55af6f75
Revises: 4f4ec0a5fcb3
Create Date: 2024-06-28 18:31:58.702271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import gpustack


# revision identifiers, used by Alembic.
revision: str = 'a16a55af6f75'
down_revision: Union[str, None] = '4f4ec0a5fcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_instances', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('users', 'foo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foo', sa.VARCHAR(), nullable=True))
    op.drop_column('model_instances', 'name')
    # ### end Alembic commands ###
