"""update model to support gpu selector

Revision ID: de42569c03ba
Revises: de256ac87390
Create Date: 2024-09-07 17:03:34.892163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import gpustack


# revision identifiers, used by Alembic.
revision: str = 'de42569c03ba'
down_revision: Union[str, None] = 'de256ac87390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('gpu_selector', gpustack.schemas.common.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'gpu_selector')
    # ### end Alembic commands ###
