"""add local_path

Revision ID: 004c73a5c09e
Revises: 0f7dde8b3c4b
Create Date: 2024-11-04 13:47:01.461783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import gpustack


# revision identifiers, used by Alembic.
revision: str = '004c73a5c09e'
down_revision: Union[str, None] = '0f7dde8b3c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('local_path')

    with op.batch_alter_table('model_instances', schema=None) as batch_op:
        batch_op.drop_column('local_path')

    # ### end Alembic commands ###
