"""update worker, model, model instance to support distributed inference

Revision ID: de256ac87390
Revises: 8277680cfcb7
Create Date: 2024-09-04 11:37:20.841240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import gpustack


# revision identifiers, used by Alembic.
revision: str = 'de256ac87390'
down_revision: Union[str, None] = '8277680cfcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_instances', sa.Column('gpu_indexes', sa.JSON(), nullable=True))
    op.add_column('model_instances', sa.Column('distributed_servers', gpustack.schemas.common.JSON(), nullable=True))
    op.drop_column('model_instances', 'gpu_index')
    op.add_column('models', sa.Column('placement_strategy', sa.Enum('SPREAD', 'BINPACK', name='placementstrategyenum'), nullable=False))
    op.add_column('models', sa.Column('partial_offload', sa.Boolean(), nullable=False))
    op.add_column('models', sa.Column('distributed_inference_across_workers', sa.Boolean(), nullable=False))
    op.add_column('models', sa.Column('worker_selector', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'worker_selector')
    op.drop_column('models', 'distributed_inference_across_workers')
    op.drop_column('models', 'partial_offload')
    op.drop_column('models', 'placement_strategy')
    op.add_column('model_instances', sa.Column('gpu_index', sa.INTEGER(), nullable=True))
    op.drop_column('model_instances', 'distributed_servers')
    op.drop_column('model_instances', 'gpu_indexes')
    # ### end Alembic commands ###
