"""GPUStack v0.7.0

Revision ID: 3c0e318142b6
Revises: cbbc03c88985
Create Date: 2025-07-29 14:25:05.299418

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3c0e318142b6'
down_revision: Union[str, None] = 'cbbc03c88985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=False, server_default='local'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('source')
    # ### end Alembic commands ###
