"""GPUStack v0.7.1

Revision ID: d19176de3b74
Revises: cbbc03c88985
Create Date: 2025-08-05 16:05:05.299418

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import gpustack


# revision identifiers, used by Alembic.
revision: str = 'd19176de3b74'
down_revision: Union[str, None] = 'cbbc03c88985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=255), nullable=False, server_default='Local'))
        batch_op.add_column(sa.Column('avatar_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('avatar_url')
    # ### end Alembic commands ###
