"""add image_name and run_command to models table, add inference_backends table

Revision ID: nrxtab43e8j8
Revises: cbbc03c88985
Create Date: 2025-09-17 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'nrxtab43e8j8'
down_revision: Union[str, None] = 'f3d36b2d11f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add image_name column to models table
    op.add_column('models', sa.Column('image_name', sa.String(length=255), nullable=True))
    
    # Add run_command column to models table
    op.add_column('models', sa.Column('run_command', sa.String(length=255), nullable=True))
    
    # Create inference_backends table
    op.create_table(
        'inference_backends',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('backend_name', sa.String(length=255), nullable=False),
        sa.Column('default_version', sa.String(length=255), nullable=True, default=''),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('default_run_command', sa.String(length=255), nullable=True, default=''),
        sa.Column('health_check_path', sa.String(length=255), nullable=True, default=''),
        sa.Column('version_configs', sa.JSON(), nullable=True),
        sa.Column('default_backend_param', sa.JSON(), nullable=True),
        sa.Column('allowed_proxy_uris', sa.JSON(), nullable=True),
        sa.Column('is_build_in', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('backend_name')
    )
    
    # Create indexes for inference_backends table
    op.create_index(op.f('ix_inference_backends_backend_name'), 'inference_backends', ['backend_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop inference_backends table indexes
    op.drop_index(op.f('ix_inference_backends_backend_name'), table_name='inference_backends')
    
    # Drop inference_backends table
    op.drop_table('inference_backends')
    
    # Remove run_command column from models table
    op.drop_column('models', 'run_command')
    
    # Remove image_name column from models table
    op.drop_column('models', 'image_name')
    # ### end Alembic commands ###
