"""update gpu instances

Revision ID: c0faf55a20e8
Revises: 03b30f8963f6
Create Date: 2026-05-13 23:40:00.639927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import gpustack
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0faf55a20e8'
down_revision: Union[str, None] = '03b30f8963f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('gpu_instance_ssh_public_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=253),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('gpu_instance_ssh_public_keys_owner_principal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'principals', ['owner_principal_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('gpu_instance_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
        batch_op.alter_column('owner_principal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=253),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('gpu_instance_templates_owner_principal_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'principals', ['owner_principal_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('gpu_instance_templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('gpu_instance_templates_owner_principal_id_fkey'), 'principals', ['owner_principal_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=253),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('owner_principal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('display_name')

    with op.batch_alter_table('gpu_instance_ssh_public_keys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('gpu_instance_ssh_public_keys_owner_principal_id_fkey'), 'principals', ['owner_principal_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=253),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
