"""gpu instances

Revision ID: 61929acb0676
Revises: 7c5e3f9a2d18
Create Date: 2026-05-28 08:52:30.654938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import gpustack

# revision identifiers, used by Alembic.
revision: str = '61929acb0676'
down_revision: Union[str, None] = '7c5e3f9a2d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('gpu_instance_persistent_volume_types',
    sa.Column('created_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', gpustack.schemas.common.UTCDateTime(), nullable=True),
    sa.Column('owner_principal_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('spec', gpustack.schemas.common.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['principals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_principal_id', 'name', name='uq_gpu_instance_persistent_volume_type_name_per_principal')
    )

    op.create_table('gpu_instance_ssh_public_keys',
    sa.Column('created_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', gpustack.schemas.common.UTCDateTime(), nullable=True),
    sa.Column('owner_principal_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('spec', gpustack.schemas.common.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['principals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_principal_id', 'name', name='uq_gpu_instance_ssh_public_key_name_per_principal')
    )

    op.create_table('gpu_instance_templates',
    sa.Column('created_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', gpustack.schemas.common.UTCDateTime(), nullable=True),
    sa.Column('owner_principal_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('spec', gpustack.schemas.common.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['principals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_principal_id', 'name', name='uq_gpu_instance_template_name_per_principal')
    )
    with op.batch_alter_table('gpu_instance_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gpu_instance_templates_manufacturer'), ['manufacturer'], unique=False)

    op.create_table('gpu_instance_persistent_volumes',
    sa.Column('created_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', gpustack.schemas.common.UTCDateTime(), nullable=True),
    sa.Column('owner_principal_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('persistent_volume_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('spec', gpustack.schemas.common.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['principals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persistent_volume_type_id'], ['gpu_instance_persistent_volume_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_principal_id', 'name', name='uq_gpu_instance_persistent_volume_name_per_principal')
    )

    op.create_table('gpu_instances',
    sa.Column('created_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gpustack.schemas.common.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', gpustack.schemas.common.UTCDateTime(), nullable=True),
    sa.Column('owner_principal_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('persistent_volume_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('spec', gpustack.schemas.common.JSON(), nullable=False),
    sa.Column('status', gpustack.schemas.common.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['principals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persistent_volume_id'], ['gpu_instance_persistent_volumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_principal_id', 'name', name='uq_gpu_instance_name_per_principal')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpu_instances')

    op.drop_table('gpu_instance_persistent_volumes')

    with op.batch_alter_table('gpu_instance_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gpu_instance_templates_manufacturer'))

    op.drop_table('gpu_instance_templates')

    op.drop_table('gpu_instance_ssh_public_keys')

    op.drop_table('gpu_instance_persistent_volume_types')

    # ### end Alembic commands ###
