#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

# Hosts the public site may fetch from and the bundled one may not. Checking the
# output rather than the config is what makes this hard to regress: the ways a
# page starts reaching out again — a theme override, a new markdown extension, a
# plugin that inlines a CDN script — are not visible in mkdocs.offline.yml.
EXTERNAL_HOSTS="unpkg\.com|fonts\.googleapis\.com|fonts\.gstatic\.com|buttons\.github\.io|img\.shields\.io|raw\.githubusercontent\.com"

# What the bundled site puts in its header, and the only way a reader can tell one
# copy from another. A release number cannot do that job here: the documentation
# ships on its own cadence, so two copies claiming the same release can hold
# different pages. A date and a commit identify the build itself.
#
# An image build passes DOCS_COMMIT in, because the documentation stage has no
# .git to ask; anywhere else it comes from the checkout. A build that can resolve
# neither is a hard error rather than a date-only stamp: the whole point of the
# stamp is telling two copies apart, and one that cannot name its commit answers
# nobody's question while still looking like it did.
function docs_stamp() {
  local commit
  commit="${DOCS_COMMIT:-}"

  # hack/lib/version.sh yields "unknown" when it finds no git at all, and that
  # travels here through the image build's --build-arg like any other value.
  if [[ "${commit}" == "unknown" ]]; then
    commit=""
  fi
  if [[ -z "${commit}" ]]; then
    commit="$(git -C "${ROOT_DIR}" rev-parse HEAD 2>/dev/null || true)"
  fi
  if [[ -z "${commit}" ]]; then
    echo "error: cannot determine the commit to stamp the documentation with." >&2
    echo "       build from a git checkout, or pass DOCS_COMMIT=<sha>." >&2
    return 1
  fi

  # Shortened here rather than by the caller, because the callers disagree:
  # version.sh hands over a full sha while a checkout could be asked for either.
  # Seven digits is what hack/build.sh already stamps the wheel with.
  echo "$(date -u '+%Y-%m-%d') (${commit:0:7})"
}

function build_public() {
  uv run mkdocs build
}

function build_offline() {
  local site_dir="${ROOT_DIR}/gpustack/help"
  # Generated instead of committed because the stamp changes with every build, and
  # kept out of git so that no YAML hook has to make sense of a file nobody edits.
  local config="${ROOT_DIR}/mkdocs.offline.generated.yml"

  # Resolved into a variable, and by an assignment of its own, because that is the
  # only shape errexit sees: a `$(...)` inside the heredoc below would have its
  # failure swallowed by the successful `cat`, and `local stamp="$(...)"` would
  # have it swallowed by the `local` builtin's own exit status. Either way the
  # site would be built with a blank stamp instead of not being built at all.
  local stamp
  stamp="$(docs_stamp)"

  # The stamp travels as an extra rather than in site_name, which Material also
  # uses to build every page title: a title carrying a build hash would follow
  # the reader into their tabs, bookmarks and history. extra is a mapping, so
  # INHERIT merges this in rather than replacing what mkdocs.offline.yml sets.
  cat >"${config}" <<EOF
# Generated by hack/build-docs.sh. Edit mkdocs.offline.yml instead.
INHERIT: mkdocs.offline.yml
extra:
  docs_stamp: '${stamp}'
EOF

  uv run mkdocs build \
    --config-file "${config}" \
    --site-dir "${site_dir}"

  # The search index is the one file where compressing pays — ~1.2 MB, and it is
  # requested by its own name, so PrecompressedStaticFiles finds the .gz sibling
  # with no change to the server. Pages are requested as directories, whose .gz
  # cannot exist, so gzipping them would produce files nothing ever asks for.
  gzip --best --force --keep "${site_dir}/search/search_index.json"

  if grep -rlE "https://(${EXTERNAL_HOSTS})" "${site_dir}" --include="*.html"; then
    echo "error: the pages above still fetch from the network" >&2
    return 1
  fi
}

#
# main
#

case "${1:-}" in
'')
  build_public
  ;;
--offline | offline)
  build_offline
  ;;
*)
  echo "usage: $(basename "${0}") [--offline]" >&2
  exit 1
  ;;
esac
