#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

# Hosts the public site may fetch from and the bundled one may not. Checking the
# output rather than the config is what makes this hard to regress: the ways a
# page starts reaching out again — a theme override, a new markdown extension, a
# plugin that inlines a CDN script — are not visible in mkdocs.offline.yml.
EXTERNAL_HOSTS="unpkg\.com|fonts\.googleapis\.com|fonts\.gstatic\.com|buttons\.github\.io|img\.shields\.io|raw\.githubusercontent\.com"

# What the bundled site puts in its header, and the only way a reader can tell one
# copy from another. A release number cannot do that job here: the documentation
# ships on its own cadence, so two copies claiming the same release can hold
# different pages. A date and a commit identify the build itself.
#
# An image build passes DOCS_COMMIT in, because the documentation stage has no
# .git to ask. Anywhere else it comes from the checkout, and a copy built without
# either says only the date rather than inventing a commit.
function docs_stamp() {
  local stamp commit
  stamp="$(date -u '+%Y-%m-%d')"

  commit="${DOCS_COMMIT:-}"
  if [[ -z "${commit}" ]]; then
    commit="$(git -C "${ROOT_DIR}" rev-parse --short HEAD 2>/dev/null || true)"
  fi
  if [[ -n "${commit}" ]]; then
    stamp="${stamp} (${commit})"
  fi

  echo "${stamp}"
}

function build_public() {
  uv run mkdocs build
}

function build_offline() {
  local site_dir="${ROOT_DIR}/gpustack/help"
  # Generated instead of committed because the stamp changes with every build, and
  # kept out of git so that no YAML hook has to make sense of a file nobody edits.
  local config="${ROOT_DIR}/mkdocs.offline.generated.yml"

  # The stamp travels as an extra rather than in site_name, which Material also
  # uses to build every page title: a title carrying a build hash would follow
  # the reader into their tabs, bookmarks and history. extra is a mapping, so
  # INHERIT merges this in rather than replacing what mkdocs.offline.yml sets.
  cat >"${config}" <<EOF
# Generated by hack/build-docs.sh. Edit mkdocs.offline.yml instead.
INHERIT: mkdocs.offline.yml
extra:
  docs_stamp: '$(docs_stamp)'
EOF

  uv run mkdocs build \
    --config-file "${config}" \
    --site-dir "${site_dir}"

  # The search index is the one file where compressing pays — ~1.2 MB, and it is
  # requested by its own name, so PrecompressedStaticFiles finds the .gz sibling
  # with no change to the server. Pages are requested as directories, whose .gz
  # cannot exist, so gzipping them would produce files nothing ever asks for.
  gzip --best --force --keep "${site_dir}/search/search_index.json"

  if grep -rlE "https://(${EXTERNAL_HOSTS})" "${site_dir}" --include="*.html"; then
    echo "error: the pages above still fetch from the network" >&2
    return 1
  fi
}

#
# main
#

case "${1:-}" in
'')
  build_public
  ;;
--offline | offline)
  build_offline
  ;;
*)
  echo "usage: $(basename "${0}") [--offline]" >&2
  exit 1
  ;;
esac
