version: "3.8"
name: gpustack-worker

services:
  gpustack-worker:
    image: gpustack/gpustack
    restart: always
    ipc: host
    volumes:
      - gpustack-data:/var/lib/gpustack
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    command: --server-url http://myserver --registration-token mytoken # replace with actual server URL and registration token
    network_mode: host

volumes:
  gpustack-data: {}
