{
 "title": "Higress Dashboard",
 "description": "Higress Ingress Controller Dashboard\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "gateway",
    "query": {
     "query": "label_values(envoy_server_live, higress)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downstream Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(envoy_http_downstream_rq_total{higress=\"$gateway\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Downstream Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq{higress=\"$gateway\", response_code_class!=\"5xx\"}[5m])) / sum(irate(envoy_http_downstream_rq_total{higress=\"$gateway\"}[5m]))"
    }
   ]
  },
  {
   "title": "Downstream Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(envoy_http_downstream_rq_time_bucket{higress=\"$gateway\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(envoy_http_downstream_rq_time_bucket{higress=\"$gateway\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_http_downstream_rq_time_bucket{higress=\"$gateway\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_rq_time_sum{higress=\"$gateway\"}[1m])) / sum(irate(envoy_http_downstream_rq_time_count{higress=\"$gateway\"}[1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "TCP Received Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{higress=\"$gateway\"}[1m]))"
    }
   ]
  },
  {
   "title": "Upstream Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(envoy_cluster_upstream_rq_total{higress=\"$gateway\"}[5m])), 0.001)"
    }
   ]
  },
  {
   "title": "Upstream Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq{higress=\"$gateway\", response_code_class!=\"5xx\"}[5m])) / sum(irate(envoy_cluster_upstream_rq_total{higress=\"$gateway\"}[5m]))"
    }
   ]
  },
  {
   "title": "Upstream Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(envoy_cluster_upstream_rq_time_bucket{higress=\"$gateway\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(envoy_cluster_upstream_rq_time_bucket{higress=\"$gateway\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_cluster_upstream_rq_time_bucket{higress=\"$gateway\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_time_sum{higress=\"$gateway\"}[1m])) / sum(irate(envoy_cluster_upstream_rq_time_count{higress=\"$gateway\"}[1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "TCP Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total{higress=\"$gateway\"}[1m]))"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(sum(envoy_server_memory_allocated{higress=\"$gateway\"}) by (pod_name))",
     "legendFormat": "Envoy(Allocated)"
    },
    {
     "expr": "avg(sum(istio_agent_go_memstats_alloc_bytes{higress=\"$gateway\"}) by (pod_name))",
     "legendFormat": "Agent(Allocated)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_agent_process_cpu_seconds_total{higress=\"$gateway\"}[1m]))",
     "legendFormat": "Agent process"
    }
   ]
  },
  { "title": "XDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Envoy Details",
   "type": "graph",
   "description": "Shows details about Envoy proxies in the mesh",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Connections"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_connect_fail{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Connection Failures"
    },
    {
     "expr": "sum(increase(envoy_server_hot_restart_epoch[1m]))",
     "legendFormat": "Envoy Restarts"
    }
   ]
  },
  {
   "title": "XDS Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{cluster_name=\"xds-grpc\"})",
     "legendFormat": "XDS Active Connections"
    }
   ]
  },
  {
   "title": "XDS Requests Size",
   "type": "graph",
   "description": "Shows the size of XDS requests and responses",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max(rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Response Bytes Max"
    },
    {
     "expr": "quantile(0.5, rate(envoy_cluster_upstream_cx_rx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Response Bytes Average"
    },
    {
     "expr": "max(rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Request Bytes Max"
    },
    {
     "expr": "quantile(.5, rate(envoy_cluster_upstream_cx_tx_bytes_total{cluster_name=\"xds-grpc\"}[1m]))",
     "legendFormat": "XDS Request Bytes Average"
    }
   ]
  },
  { "title": "Service Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "QPS Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(irate(envoy_cluster_upstream_rq_total{higress=\"$gateway\", cluster_name!=\"xds-grpc\", cluster_name!=\"zipkin\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\", cluster_name!~\".*\\\\.internal\"}[5m])) by (cluster_name)), \"service\", \"$3\", \"cluster_name\", \"outbound\\\\|([0-9]+)\\\\|(.*)\\\\|(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound\\\\|([0-9]+)\\\\|(.*)\\\\|(.*)$\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RT Top 10(Slow)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(irate(envoy_cluster_upstream_rq_time_sum{higress=\"$gateway\", cluster_name!=\"xds-grpc\", cluster_name!=\"zipkin\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\", cluster_name!~\".*\\\\.internal\"}[5m])) by (cluster_name) / sum(irate(envoy_cluster_upstream_rq_time_count{higress=\"$gateway\",cluster_name!=\"xds-grpc\", cluster_name!=\"zipkin\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\", cluster_name!~\".*\\\\.internal\"}[5m])) by (cluster_name)), \"service\", \"$3\", \"cluster_name\", \"outbound\\\\|([0-9]+)\\\\|(.*)\\\\|(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound\\\\|([0-9]+)\\\\|(.*)\\\\|(.*)$\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connection Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(envoy_cluster_upstream_cx_active{higress=\"$gateway\", cluster_name!=\"xds-grpc\", cluster_name!=\"zipkin\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\", cluster_name!~\".*\\\\.internal\"}) by (cluster_name)), \"service\", \"$3\", \"cluster_name\", \"outbound\\\\|([0-9]+)\\\\|(.*)\\\\|(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound\\\\|([0-9]+)\\\\|(.*)\\\\|(.*)$\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Requests Top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(label_replace(topk(10, sum(increase(envoy_cluster_upstream_rq{response_code_class=~\"(4|5)xx\",higress=\"$gateway\", cluster_name!=\"xds-grpc\", cluster_name!=\"zipkin\", cluster_name!=\"prometheus_stats\", cluster_name!=\"agent\", cluster_name!=\"BlackHoleCluster\", cluster_name!=\"sds-grpc\", cluster_name!~\".*\\\\.internal\"}[5m])) by (cluster_name)), \"service\", \"$3\", \"cluster_name\", \"outbound\\\\|([0-9]+)\\\\|(.*)\\\\|(.*)$\"), \"port\", \"$1\", \"cluster_name\", \"outbound\\\\|([0-9]+)\\\\|(.*)\\\\|(.*)$\")",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}