"""Where the packaged Helm chart lives, and how a cluster reaches it.

The chart is packaged into the UI's static tree at build time (see
``hack/install.sh``), which the server already mounts at ``/static``. So it is
served without a route of its own, and the URL the in-cluster bootstrap Job
installs from is just the server's own address plus a fixed path.

Serving it from the server rather than baking it into an image is what keeps the
chart and the registration manifest in step: both come from the same process, so
a cluster can never be handed a manifest that references values a different
chart version would read. It also needs no egress — the cluster must already
reach the server to register at all.
"""

import hashlib
import pathlib
from functools import lru_cache

# Relative to ``gpustack/ui``, which ``gpustack/routes/ui.py`` mounts as
# ``/static``. Fixed rather than versioned: the manifest that references this is
# regenerated by the same server that serves it, so putting a version in the URL
# would be a second thing to keep in step for no gain.
CHART_STATIC_PATH = "static/charts/gpustack-chart.tgz"

_UI_DIR = pathlib.Path(__file__).resolve().parents[1] / "ui"


def chart_asset_path() -> pathlib.Path:
    """Filesystem path of the packaged chart inside this installation."""
    return _UI_DIR / CHART_STATIC_PATH


def chart_available() -> bool:
    """Whether this installation actually carries the packaged chart.

    A source checkout that has not run ``make deps`` does not, and neither does
    one built with ``CHART_PACKAGE=false``. Callers rendering a manifest that
    points at the chart check this first, so the failure names the missing build
    step instead of surfacing as a 404 inside the cluster minutes later.
    """
    return chart_asset_path().is_file()


def chart_digest() -> str:
    """Digest of the packaged chart this installation serves.

    Two things rest on it. It decides whether an already-installed release is up
    to date — the URL cannot, since it carries no version, so a server upgrade
    shipping a new chart serves different bytes at the same address and a
    cluster comparing anything else would skip the upgrade. And it authenticates
    the download: the Job checks it, which is what lets the fetch skip
    certificate verification.

    Cached on the asset's identity rather than recomputed per manifest fetch.
    The file is written once at build time, so the mtime and size cannot change
    without the installation changing — and every registration hits this.
    """
    asset = chart_asset_path()
    stat = asset.stat()
    return _digest_of(asset, stat.st_mtime_ns, stat.st_size)


@lru_cache(maxsize=4)
def _digest_of(asset: pathlib.Path, mtime_ns: int, size: int) -> str:
    digest = hashlib.sha256()
    with asset.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def chart_download_url(server_url: str) -> str:
    """URL an in-cluster Job can install the chart from.

    ``server_url`` is the address the cluster already registers against, so
    whatever reachability and TLS story applies to registration applies here
    too, unchanged.
    """
    return f"{server_url.rstrip('/')}/{CHART_STATIC_PATH}"
