#!/command/with-contenv /bin/bash
# shellcheck shell=bash

SCRIPT_ROOT=/etc/s6-overlay/scripts
source "$SCRIPT_ROOT/base.sh"
# The config should be ready before starting
source "$GPUSTACK_GATEWAY_CONFIG"
source "$SCRIPT_ROOT/default-variables.sh"

set -e

readinessCheck "Higress Controller" "$GATEWAY_CONTROLLER_GRPC_PORT" 2
