#!/command/with-contenv /bin/bash
# shellcheck shell=bash
# ================================
# Postgres longrun service
# ================================

SCRIPT_ROOT=/etc/s6-overlay/scripts
source "$SCRIPT_ROOT/base.sh"

# Stage1: Load role and flag

ROLE_FILE="/var/lib/gpustack/run/role"
FLAG_START_EMBEDDED_DATABASE_FILE="/var/lib/gpustack/run/flag_start_embedded_database"
FLAG_EMBEDDED_DATABASE_PORT_FILE="/var/lib/gpustack/run/flag_embedded_database_port"

ROLE=""
EMBEDDED_DATABASE_FLAG=""
EMBEDDED_DATABASE_PORT="5432"

if [ -f "$ROLE_FILE" ]; then
	ROLE=$(cat "$ROLE_FILE")
fi
if [ -f "$FLAG_START_EMBEDDED_DATABASE_FILE" ]; then
	EMBEDDED_DATABASE_FLAG=$(cat "$FLAG_START_EMBEDDED_DATABASE_FILE")
fi

if [ "$ROLE" != "server" ] || [ "$EMBEDDED_DATABASE_FLAG" != "1" ]; then
	echo "[INFO] Not server or not need to start postgres, sleeping."
	exec s6-notifyoncheck \
         -d -w 2000 -n 3 \
         -- \
         sleep infinity
	exit 0
fi

if [ -f "$FLAG_EMBEDDED_DATABASE_PORT_FILE" ]; then
    EMBEDDED_DATABASE_PORT=$(cat "$FLAG_EMBEDDED_DATABASE_PORT_FILE")
fi


# Stage2: Check port availability

if isPortInUse "$EMBEDDED_DATABASE_PORT"; then
    echo "[ERROR] Port $EMBEDDED_DATABASE_PORT is already in use and required by the embedded database. Please specify a different port using --database-port."
    exit 1
fi

# Stage3: Start Postgres

PGDATA="/var/lib/gpustack/postgresql/data"
PGLOG="/var/lib/gpustack/log/postgresql"
PASS_FILE="/var/lib/gpustack/postgres_root_pass"

# Ensure data directory
if [ ! -d "$PGDATA" ]; then
	mkdir -p "$PGDATA" \
		&& chown -R postgres:postgres "$PGDATA" \
		&& chmod 0700 "$PGDATA"
fi

# Ensure log directory
if [ ! -d "$PGLOG" ]; then
	mkdir -p "$PGLOG" \
		&& chown -R postgres:postgres "$PGLOG" \
		&& chmod 0755 "$PGLOG"
fi

# Password setup
ROOT_PASS=""
if [ ! -f "$PASS_FILE" ]; then
	if [ -n "$POSTGRES_PASSWORD" ]; then
		ROOT_PASS="$POSTGRES_PASSWORD"
	else
		ROOT_PASS=$(tr -dc 'A-Za-z0-9!@#$%^&*_+=' </dev/urandom | head -c 16)
		ROOT_PASS="$(tr -dc 'A-Za-z' </dev/urandom | head -c 1)${ROOT_PASS:1}"
	fi
	echo "$ROOT_PASS" > "$PASS_FILE"
	chmod 600 "$PASS_FILE"
	echo "[INFO] Postgres root password written to $PASS_FILE."
elif [ -f "$PASS_FILE" ]; then
    ROOT_PASS=$(cat "$PASS_FILE")
    echo "[INFO] Postgres root password read from $PASS_FILE."
fi

# reconfigure Postgres port
PGCONFIG_FILE=/etc/postgresql/main/postgresql.conf
gosu postgres sed -i "s/^port[[:space:]]*=[[:space:]]*[0-9]\+/port = $EMBEDDED_DATABASE_PORT/" "$PGCONFIG_FILE"

# Initialize database
if [ ! -s "$PGDATA/PG_VERSION" ]; then
    echo "[INFO] Initializing Postgres database."
	gosu postgres initdb -D "$PGDATA" > /dev/null
fi
gosu postgres pg_ctl -s -D "$PGDATA" -o "-c listen_addresses='localhost' -c port='$EMBEDDED_DATABASE_PORT'" -w start > /dev/null
if ! gosu postgres psql -p "$EMBEDDED_DATABASE_PORT" -tAc "SELECT 1 FROM pg_roles WHERE rolname='root'" | grep -q 1; then
    gosu postgres psql -p "$EMBEDDED_DATABASE_PORT" -q --command "CREATE USER root WITH PASSWORD '$ROOT_PASS';" > /dev/null
fi
if ! gosu postgres psql -p "$EMBEDDED_DATABASE_PORT" -tAc "SELECT 1 FROM pg_database WHERE datname='gpustack'" | grep -q 1; then
    gosu postgres psql -p "$EMBEDDED_DATABASE_PORT" -q --command "CREATE DATABASE gpustack OWNER root;" > /dev/null
fi
gosu postgres pg_ctl -p "$EMBEDDED_DATABASE_PORT" -s -D "$PGDATA" -m fast -w stop > /dev/null

# Start Postgres
echo "[INFO] Starting Postgres."
exec s6-notifyoncheck \
     -d -w 5000 -n 10 -s 3000 \
     -- \
     gosu postgres /usr/bin/postgres \
         -D "$PGDATA" \
         -p "$EMBEDDED_DATABASE_PORT" \
         -c config_file=/etc/postgresql/main/postgresql.conf \
         -c hba_file=/etc/postgresql/main/pg_hba.conf
