#!/bin/bash

# Following variables might be rewrited by config generated by GPUStack
DATA_DIR="${DATA_DIR:-/var/lib/gpustack}"
LOG_DIR="${LOG_DIR:-${DATA_DIR}/log}"
HIGRESS_DATA_DIR="${DATA_DIR}/higress/data"
# shellcheck disable=SC2034
HIGRESS_LOG_DIR="${LOG_DIR}/higress"
APISERVER_PORT=${APISERVER_PORT:-18443}
APISERVER_DATA_DIR="${HIGRESS_DATA_DIR}/apiserver"
EMBEDDED_KUBECONFIG_PATH="${EMBEDDED_KUBECONFIG_PATH:-${APISERVER_DATA_DIR}/kubeconfig}"
GATEWAY_HTTP_PORT="${GATEWAY_HTTP_PORT:-80}"
GATEWAY_HTTPS_PORT="${GATEWAY_HTTPS_PORT:-443}"
GATEWAY_CONCURRENCY="${GATEWAY_CONCURRENCY:-16}"
# shellcheck disable=SC2034
ISTIO_DATA_DIR="${HIGRESS_DATA_DIR}/istio-data"

if [ -n "${KUBERNETES_SERVICE_PORT}" ] && [ -n "${KUBERNETES_SERVICE_HOST}" ]; then
    # running in k8s, use in-cluster config, set EMBEDDED_KUBECONFIG_PATH to empty
    EMBEDDED_KUBECONFIG_PATH=""
fi
