FROM registry.cn-shanghai.aliyuncs.com/insi-tech/vllm:hpcc.ai3.0.0.5-torch2.6-py310-ubuntu22.04-amd64

RUN apt-get update && apt-get install -y \
    git \
    curl \
    wget \
    tzdata \
    iproute2 \
    tini \
    git-lfs \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PATH /opt/conda/bin:$PATH

RUN pip --version
    
COPY .. /workspace/gpustack
RUN cd /workspace/gpustack && make build
RUN pip install /workspace/gpustack/dist/*.whl && pip cache purge

RUN gpustack download-tools

ENTRYPOINT [ "tini", "--", "gpustack", "start" ]
