FROM crpi-thyzhdzt86bexebt.cn-hangzhou.personal.cr.aliyuncs.com/gpustack_ai/gpustack:iluvator-corex4.2.0-vllm0.8.3-py3.10 AS build

RUN apt-get update && apt-get install -y \
    git \
    curl

COPY .. /workspace/gpustack
RUN cd /workspace/gpustack && make build

FROM crpi-thyzhdzt86bexebt.cn-hangzhou.personal.cr.aliyuncs.com/gpustack_ai/gpustack:iluvator-corex4.2.0-vllm0.8.3-py3.10 AS runtime

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    wget \
    tzdata \
    iproute2 \
    tini \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=build /workspace/gpustack/dist/*.whl /dist/
RUN pip install /dist/*.whl && \
    pip cache purge && \
    rm -rf /dist

RUN gpustack download-tools

ENTRYPOINT [ "tini", "--", "gpustack", "start" ]
