name: Install Script MacOS

on:
  push:
    branches:
      - feat/12
    # paths:
    #   - "install.sh"
    #   - ".github/workflows/install-script.yml"
  pull_request:
    branches:
      - main
    paths:
      - "install.sh"
      - ".github/workflows/install-script.yml"
  workflow_dispatch: {}

jobs:
  linux-ubuntu-build:
    name: Build Wheel
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [X64]
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build
        run: |
          make build

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-dist
          path: dist/*.whl

  linux-ubuntu-install-test:
    name: Test Install
    needs: linux-ubuntu-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Download wheel artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.os }}-dist
          path: ./dist

      - name: Run install script
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            if [[ "${{ runner.arch }}" == "X64" ]]; then
              INSTALL_PACKAGE_SPEC=$(ls dist/*x86_64.whl)
            elif [[ ${{ runner.arch }} == "ARM64" ]]; then
              INSTALL_PACKAGE_SPEC=$(ls dist/*aarch64.whl)
            fi
          else
            export INSTALL_PACKAGE_SPEC=$(ls dist/*.whl)
          fi

          echo "${{ runner.arch }}"
          echo "INSTALL_PACKAGE_SPEC: $INSTALL_PACKAGE_SPEC"
          INSTALL_PACKAGE_SPEC=$(echo dist/*.whl) ./install.sh

      - name: Verify installation
        run: |
          gpustack version
          curl --fail --retry 5 --retry-delay 2 --retry-all-errors http://127.0.0.1/readyz
